config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/vouchers', to: 'pages#vouchers'

  resources :merchants
  devise_for :users
  # root "deals#index"
  
  resources :deals do 
    member do 
      post 'apply'
    end
  end

  resources :charges



  # get "/vouchers/:id", to: "vouchers#show", as: 'voucher'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  include ImageUploader[:image]
  belongs_to :user
  has_many :deals

  def full_address
    #e.g. "120 Spencer st, Melbourne, Victoria, 3000, AU"
    "#{street}, #{city}, #{state}, #{postcode}"
  end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :set_merchant, only: [:show, :edit, :update, :destroy]

  # GET /merchants
  # GET /merchants.json
  def index
    @merchants = Merchant.all
    authorize @merchants
    @merchants = policy_scope(Merchant)
  end

  # GET /merchants/1
  # GET /merchants/1.json
  def show
  end

  # GET /merchants/new
  def new
    @merchant = Merchant.new
    authorize @merchant
  end

  # GET /merchants/1/edit
  def edit
  end

  # POST /merchants
  # POST /merchants.json
  def create
    @merchant = Merchant.new(merchant_params)
    @merchant.user = current_user
    authorize @merchant

    respond_to do |format|
      if @merchant.save
        format.html { redirect_to @merchant, notice: 'Merchant was successfully created.' }
        format.json { render :show, status: :created, location: @merchant }
        redirect_to new_charge_path
        return
      else
        format.html { render :new }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merchants/1
  # PATCH/PUT /merchants/1.json
  def update
    respond_to do |format|
      if @merchant.update(merchant_params)
        format.html { redirect_to @merchant, notice: 'Merchant was successfully updated.' }
        format.json { render :show, status: :ok, location: @merchant }
      else
        format.html { render :edit }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merchants/1
  # DELETE /merchants/1.json
  def destroy
    @merchant.destroy
    respond_to do |format|
      format.html { redirect_to merchants_url, notice: 'Merchant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merchant
      @merchant = Merchant.find(params[:id])
      authorize @merchant
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merchant_params
      params.require(:merchant).permit(:user_id, :name, :description, :image, :remove_image, :street, :city, :state, :postcode, :latitude, :longitude, :website_url, :facebook_id)
    end

    def authorize_merchant
      authorize policy_scope(Merchant)
    end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/_form.html.erb
<div class="container-body">
  <%= form_with(model: merchant, local: true) do |form| %>
    <% if merchant.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(merchant.errors.count, "error") %> prohibited this merchant from being saved:</h2>

        <ul>
        <% merchant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, id: :merchant_name %>
    </div>

    <div class="field">
      <%= form.label :street %>
      <%= form.text_field :street, id: :merchant_street %>
    </div>

    <div class="field">
      <%= form.label :city %>
      <%= form.text_field :city, id: :merchant_city %>
    </div>

    <div class="field">
      <%= form.label :state %>
      <%= form.text_field :state, id: :merchant_state %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description, id: :merchant_description %>
    </div>

    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image, id: :merchant_image_data %>
    </div>
    <% if merchant.image_data? %>
      <div class="field">
        <%= image_tag merchant.image_url(:thumb) %>
      </div>
      <div class="field">
        Remove attachment: <%= form.check_box :remove_image %>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :website_url %>
      <%= form.text_field :website_url, id: :merchant_website_url %>
    </div>

    <div class="field">
      <%= form.label :facebook_id %>
      <%= form.text_field :facebook_id, id: :merchant_facebook_id %>
    </div>

    <div class="actions merchant-submit">
      <%= form.submit "UPDATE"%>
    </div>
  <% end %>
</div>

app/views/merchants/edit.html.erb
<div class= "container-headline">
    <h1>Editing Merchant</h1>
</div>

<%= render 'form', merchant: @merchant %>

app/views/merchants/index.html.erb
<p id="notice"><%= notice %></p>
<div class= "container-headline">
  <h1>Merchants</h1>
</div>

<div class="container-body">
  <table>
    <tbody>
      <% @merchants.each do |merchant| %>
        <tr>
          <td><%= merchant.name %></td>
          <td><%= link_to 'Show', merchant %></td>
          <td><%= link_to 'Edit', edit_merchant_path(merchant) %></td>
          <td><%= link_to 'Delete', merchant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="container-body">
  <%= link_to 'New Merchant', new_merchant_path %>
</div>

app/views/merchants/new.html.erb
<h1>Please fill below about your shop!</h1>
<h3>&#42;required</h3>

<%= render 'form', merchant: @merchant %>

<%= link_to 'Back', merchants_path %>

app/views/merchants/show.html.erb
<p id="notice"><%= notice %></p>

<div class= "container-headline">
  <%= link_to 'Create a new deal', new_deal_path(@merchant) if current_user == @merchant.user %>
</div>

<div class= "container-body">
  <p>
    <%= image_tag @merchant.image_url(:thumb) unless @merchant.image.blank?%>
  </p>
</div>

<div class= "container-body">
  <p>
    <strong>Name:</strong>
    <%= @merchant.name %>
  </p>
</div>

<div class= "container-body">
  <p>
    <strong>About:</strong>
    <%= @merchant.description %>
  </p>
</div>

<div class= "container-body">
  <p>
    <strong>Address:</strong>
    <%= @merchant.full_address %>
  </p>
</div>
<div class= "container-body">
  <p>
    <strong>Website url:</strong>
    <%= @merchant.website_url %>
  </p>
</div>

<div class= "container-body">
  <p>
    <strong>Facebook:</strong>
    <%= @merchant.facebook_id %>
  </p>
</div>

<div class= "container-body">
  <strong>All Deals:</strong>
      <% @merchant.deals.each do |d|  %>
        <ul>
          <li><%= d.title %> <%= link_to 'View', deal_path(d) %></li>
        </ul>
      <% end %>
</div>

<div class= "container-body">
  <%= link_to 'Edit', edit_merchant_path(@merchant) if current_user == @merchant.user %>
</div>