config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/vouchers', to: 'pages#vouchers'

  resources :merchants
  devise_for :users
  # root "deals#index"
  
  resources :deals do 
    member do 
      post 'apply'
    end
  end

  resources :charges



  # get "/vouchers/:id", to: "vouchers#show", as: 'voucher'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/deal.rb
class Deal < ApplicationRecord
    include ImageUploader[:image]
    belongs_to :merchant
    has_many :vouchers

    def self.search_by_name(search)
        where("LOWER(description) LIKE ?", "%#{search.downcase}%")
    end

    # def self.voucher_limit
    #     Voucher.where(@deal).count < @deal.quantity && Voucher.where(@deal, @deal.user).count < @deal.voucher_limit_per_user
    # end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: [:show, :edit, :update, :destroy, :apply]
  
  # GET /deals
  # GET /deals.json
  def index
    unless params[:deals].present?
      @deals = Deal.all
      authorize @deals
    else
      deal_description = params[:deals][:search]
      @deals = Deal.search_by_name(deal_description)
    end
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
  end

  # GET /deals/new
  def new
    @deal = Deal.new
    authorize @deal
  end

  # GET /deals/1/edit
  def edit
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = Deal.new(deal_params)
    @deal.merchant = Merchant.find(current_user.id)
    authorize @deal
    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render :show, status: :created, location: @deal }
      else
        format.html { render :new }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1
  # PATCH/PUT /deals/1.json
  def update
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { render :show, status: :ok, location: @deal }
      else
        format.html { render :edit }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  def apply
    
    flash[:notice] = "You applied for the deal!"
    # create a voucher using the Voucher model (Voucher.new)
    @voucher = Voucher.new
    # Voucher is for Voucher.deal =  @deal
    @voucher.deal = @deal
    # Voucher is for User Voucher.user = current_user
    @voucher.user = current_user
    # Save the new Voucher

    # unless @deal.vouchers.voucher_limit
    #   @voucher.save
    # # redirect_to root_path
    # else
    #   flash[:notice] = "This deal is not available!"
    # end


    if @voucher.save
      VoucherMailer.voucher_mail(@voucher).deliver_now
      # format.html{ redirect_to @voucher }
      redirect_to root_path
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal.destroy
    respond_to do |format|
      format.html { redirect_to deals_url, notice: 'Deal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deal
      @deal = Deal.find(params[:id])
      authorize @deal
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deal_params
      params.require(:deal).permit(:title, :description, :image, :original_price, :offer_price, :expiry, :quantity, :voucher_limit_per_user, :charge_id)
    end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_form.html.erb
<div class="container-body">
  <%= form_with(model: deal, local: true) do |form| %>
    <% if deal.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

        <ul>
        <% deal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, id: :deal_title %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description, id: :deal_description %>
    </div>

    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image, id: :deal_image_data %>
    </div>

    <% if deal.image_data? %>
      <div class="field">
        <%= image_tag deal.image_url(:thumb) %>
      </div>
      <div class="field">
        Remove attachment: <%= form.check_box :remove_image %>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :original_price %>
      <%= form.text_field :original_price, id: :deal_original_price %>
    </div>

    <div class="field">
      <%= form.label :offer_price %>
      <%= form.text_field :offer_price, id: :deal_offer_price %>
    </div>

    <div class="field">
      <%= form.label :expiry %>
      <%= form.datetime_select :expiry, id: :deal_expiry %>
    </div>

    <div class="field">
      <%= form.label :quantity %>
      <%= form.number_field :quantity, id: :deal_quantity %>
    </div>

    <div class="field">
      <%= form.label :voucher_limit_per_user %>
      <%= form.number_field :voucher_limit_per_user, id: :deal_voucher_limit_per_user %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/deals/edit.html.erb
<div class= "container-headline">
    <h1>Editing Deal</h1>
</div>

<%= render 'form', deal: @deal %>
<div class= "container-body">
<%= link_to 'Show', @deal %>
</div>

<div class= "container-body">
<%= link_to 'Back', deals_path %>
</div>

app/views/deals/index.html.erb
<p id="notice"><%= notice %></p>

<div class= "container-headline">
  <h1>Choose today's deal!</h1>
</div>

<div class="container-filterbar">
  <%= form_with scope: :deals, method: :get, local: true do |f| %>
    <%= f.label :filter_by_keyword  %>
    <%= f.text_field :search  %>
    <%= f.submit :filter  %>
  <% end %>
</div>



<div class= "container-main">
  <% @deals.each do |deal| %>
    <div class="element">
      <div class="image">
      <%= image_tag deal.image_url(:thumb) unless deal.image.blank? %>
      </div>
      <div class="title"><%= deal.title %></div>
      <div class="address"><%= deal.merchant.full_address %></div>
      <div class="original-price">$<%= deal.original_price %></div>
      <div class="offer-price">$<%= deal.offer_price %></div>
      <div class="view"><%= link_to 'VIEW', deal %></div>
    </div>
  <% end %>
</div>

app/views/deals/new.html.erb
<div class="container-headline">
    <h1>Please fill below about a new deal!</h1>
</div>

<%= render 'form', deal: @deal %>

app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-body">
  <p>
    <%= image_tag @deal.image_url(:thumb) unless @deal.image.blank?%>
  </p>
</div>

<div class="container-body">
  <p>
    <strong>Title:</strong>
    <%= @deal.title %>
  </p>
</div>

<div class="container-body">
  <p>
    <strong>Address:</strong>
    <%= @deal.merchant.full_address %>
  </p>
</div>

<div class="container-body">
  <p>
    <strong>Original price:</strong>
    <%= @deal.original_price %>
  </p>
  <p>
    <strong>Offer price:</strong>
    <%= @deal.offer_price %>
  </p>
</div>

<div class="container-body">
  <p>
    <strong>Shop:</strong>
    <%= @deal.merchant.name %>
    <%= link_to 'More info', merchant_path(@deal) %>
  </p>
</div>

<div class="container-body">
  <p>
    <strong>Description:</strong>
    <%= @deal.description %>
  </p>
</div>

<div class="container-body">
  <p>
    <strong>Expiry:</strong>
    <%= @deal.expiry %>
  </p>
</div>

<div class="container-body">
  <p>
    <strong>Left:</strong>
    <%= @deal.quantity %>
  </p>
</div>

<div class="container-body">
  <p>
    <strong>Voucher limit per user:</strong>
    <%= @deal.voucher_limit_per_user %>
  </p>
</div>

<div class="container-body">
  <%= link_to 'GET', apply_deal_path(@deal), method: :post unless current_user == @deal.merchant.user %>
</div>

<div class="container-body">
  <%= link_to 'Edit', edit_deal_path(@deal) if current_user == @deal.merchant.user %>
</div>

<div class="container-body">
  <%= link_to 'Destroy', @deal, method: :delete, data: { confirm: 'Are you sure?' } if current_user == @deal.merchant.user %><br>
</div>