config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/vouchers', to: 'pages#vouchers'

  resources :merchants
  devise_for :users
  # root "deals#index"
  
  resources :deals do 
    member do 
      post 'apply'
    end
  end

  resources :charges



  # get "/vouchers/:id", to: "vouchers#show", as: 'voucher'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    skip_after_action :verify_authorized

    def new
    end
    
    def create
      # Amount in cents
      @amount = 500
    
      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )
    
      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => 'Rails Stripe customer',
        :currency    => 'usd'
      )
    
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$30.00</strong>!</h2>

<%= link_to 'Back to Merchant page', merchants_path %>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $30.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A registration fee"
          data-amount="3000"
          data-locale="auto"></script>
<% end %>